---
title: "edu content typer"
author: "Alexa Gray"
date: "2025-02-18"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(kableExtra)
library(googlesheets4)
```

```{r}
library(readxl)
mpa_data <- read_sheet("https://docs.google.com/spreadsheets/d/1pA9tHg_jjx9XXXxRRws8KiTv0P5nsXWR-1Oz5JyLL1o/edit?gid=1188768943#gid=1188768943")
mpa_data <- readRDS("~/MPA EDU/data/raw-ish/education_export_24April2025.Rds")
```
```{r}
content <- mpa_data |> 
  filter(!is.na(plan_id)) |> 
  distinct(plan_id, edu_content_type) |> 
  group_by(edu_content_type) |> 
  summarize(n = length(plan_id)) |> 
  mutate(percent = 100*(n/length(unique(mpa_data$plan_id)))) 

content_summary <- kable(content,
                         col.names = c("Content Type", "Number of Plans", "Percent of Plans"),
                         format = "html",
                         caption = "Summary Statistics for Content Type",
                         digits = 1)
content_summary |> 
  kable_styling(latex_options = "striped") |> 
 save_kable(file = "content_summary.png", zoom = 2)

```

