---
title: "edu what map"
author: "Alexa Gray"
date: "2025-03-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(readxl)
library(tidyverse)
library(readxl)
library(cowplot)
library(scales)
```

```{r}
# load data
orig_list <- readRDS("~/MPA EDU/data/processed/orig_list.Rds")
orig_list <- readRDS("data/raw-ish/education_export_17Apr2025.Rds")

```

```{r}
# Create binary obs
edu_what_binary <- orig_list |> 
  left_join(names, by = "plan_id") |> 
  filter(!is.na(edu_what)) |> 
  distinct(plan_id, name_abbrev, edu_what, region) |> 
  mutate(edu_what = case_when(edu_what == "Volunteer training/steward program" ~ "Volunteer, intern, and steward training programs", TRUE ~ edu_what)) |> 
  mutate(edu_what = case_when(edu_what == "Media marketing and science communications for the general publics for the general public" ~ "Media marketing and science communications for the general public", TRUE ~ edu_what)) |> 
  mutate(edu_what = recode(edu_what, `Development of broader organizational relationships` = 'Organizational relationships',
                           `Improved signage and communication of park rules` = 'Signs & park rule communication',
                           `Internal training, improved park infrastructure, and evaluation of program effectiveness` = 'Staff training & program evaluation',
                           `Media marketing and science communications for the general public` = 'Public materials & science communication',
                          `Presentations, workshops, and outreach events` = 'Presentations & outreach events',
                          `School presentations, workshops, and educational programs` = 'School programs',
                          `Volunteer, intern, and steward training programs` = 'Volunteer & steward training',
                          `Training and targeted material for local livelihoods` = 'Material & training for local livelihoods')) |> 
  group_by(plan_id, name_abbrev, edu_what, region) |> 
  summarize(binary = n()) |> 
  pivot_wider(names_from = edu_what, values_from = binary, values_fill = 0) |> 
  pivot_longer(cols = 4:11) |> 
  mutate(value = if_else(value > 0, 1, 0)) |> 
  mutate(name= as.factor(name), value = as.factor(value))
edu_what_binary
```

```{r}
column_order <- edu_what_binary %>% 
  mutate(value = if_else(value == "0", 0, 1)) %>% 
  group_by(name) %>% 
  summarize(total = sum(value)) %>%  # use this to create a factor with levels for the columns
  mutate(name = fct_reorder(name, total, .desc = TRUE))

row_order <- edu_what_binary %>% 
  mutate(value = if_else(value == "0", 0, 1)) %>% 
  group_by(name_abbrev) %>% 
  summarize(total = sum(value), .groups = 'drop') %>% 
  mutate(name_abbrev = fct_reorder(name_abbrev, total))

edu_what_binary <- edu_what_binary %>% 
  mutate(name = factor(name, levels = levels(column_order$name))) |> 
  mutate(name_abbrev = factor(name_abbrev, levels = levels(row_order$name_abbrev)))
# same for the plan id column

# Better colors, and make the x-axis label legible
# Reorder the strategies (x-axis): use factor reorder by how prevalent the strategy is 
# Instead of plan_id # on the y-axis, use the abbreviated name
# > ?ggh4x::facet_nested - can check to see more arguments about where to put the labels for the different regions (e.g. top vs. right)
# Consider reordering the plans within each region, so the ones that have the most strategies go towards the top

```



```{r}

edu_what_binary$value <- factor(edu_what_binary$value, levels = c("1", "0"))
heatmap_draft1 <- ggplot(edu_what_binary |> 
                           filter(region %in% c("Pacific", "Indian" )),
                         aes(x = name, y = name_abbrev, fill = value)) +
  geom_tile(color = "white",  show.legend = FALSE) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12),
        axis.title.y = element_text(size = 16)) +
  scale_x_discrete(labels = label_wrap(width = 30), expand = c(0, 0)) +
 # facet_grid(~region, scales = "free")
  ggh4x::facet_nested(region~., scales = "free", space = "free") +
  labs(x = NULL, y = "MPA by Region", fill = NULL) +
  scale_fill_manual(labels = c("0" = "no", "1" = "yes"),
                      values = c("0" = "#d3dce0",
                                 "1" = "#377899"))

heatmap_draft2 <- ggplot(edu_what_binary |> 
                           filter(!(region %in% c("Pacific", "Indian" ))),
                         aes(x = name, y = name_abbrev, fill = value)) +
  geom_tile(color = "white") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 12)) +
  scale_x_discrete(labels = label_wrap(width = 30), expand = c(0, 0)) +
 # facet_grid(~region, scales = "free")
  ggh4x::facet_nested(region~., scales = "free", space = "free") +
  labs(x = NULL, y = NULL, fill = NULL) +
  scale_fill_manual(labels = c("1" = "yes", "0" = "no"),
                      values = c("0" = "#d3dce0",
                                 "1" = "#377899"))

heatmap_draft <- plot_grid(heatmap_draft1, heatmap_draft2)
# heatmap_draft1
# heatmap_draft2

## order strategies -> convert to factor
ggsave("heatmap_draft.png", heatmap_draft, width = 17, height = 18, units = "in")
```



```{r}

plan_names <- readRDS(file.path("~/MPA EDU/data/processed/exported-plan-names.Rds"))


names <- plan_names %>% 
  select(plan_id, name_english) %>% 
  mutate(name_abbrev = str_replace(name_english, "Marine Protected Area", "MPA")) %>% 
  mutate(name_abbrev = str_replace(name_abbrev, "Marine Reserve", "MR")) %>% 
  mutate(name_abbrev = str_replace(name_abbrev, "National Park", "NP")) %>% 
  mutate(name_abbrev = str_replace(name_abbrev, "Marine Park", "MP")) %>% 
  mutate(name_abbrev = str_replace(name_abbrev, "Biosphere Reserve", "BR")) %>% 
  mutate(name_abbrev = str_replace(name_abbrev, "National Marine Sanctuary", "NMS")) %>% 
  mutate(name_abbrev = str_replace(name_abbrev, "Marine National Monument", "MNM")) %>%  
  mutate(name_abbrev = str_replace(name_abbrev, "Conservation Area", "CA")) %>%
  mutate(name_abbrev = str_replace(name_abbrev, "Ecological Station", "ES")) %>%
  mutate(name_abbrev = str_replace(name_abbrev, "National Wildlife Refuge", "NWR")) %>% 
  mutate(name_abbrev = str_remove(name_abbrev, "Parks and ")) 




```

